import os

from dotenv import load_dotenv

load_dotenv()


MONITOR_INTERVAL = int(os.getenv("MONITOR_INTERVAL", "5"))

CPU_WARNING_THRESHOLD = float(
    os.getenv("CPU_WARNING_THRESHOLD", "80")
)

CPU_CRITICAL_THRESHOLD = float(
    os.getenv("CPU_CRITICAL_THRESHOLD", "90")
)

MEMORY_WARNING_THRESHOLD = float(
    os.getenv("MEMORY_WARNING_THRESHOLD", "75")
)

MEMORY_CRITICAL_THRESHOLD = float(
    os.getenv("MEMORY_CRITICAL_THRESHOLD", "90")
)

DISK_WARNING_THRESHOLD = float(
    os.getenv("DISK_WARNING_THRESHOLD", "80")
)

DISK_CRITICAL_THRESHOLD = float(
    os.getenv("DISK_CRITICAL_THRESHOLD", "90")
)

PROCESS_CPU_WARNING_THRESHOLD = float(
    os.getenv("PROCESS_CPU_WARNING_THRESHOLD", "80")
)

PROCESS_CPU_CRITICAL_THRESHOLD = float(
    os.getenv("PROCESS_CPU_CRITICAL_THRESHOLD", "90")
)

PROCESS_MEMORY_WARNING_THRESHOLD = float(
    os.getenv("PROCESS_MEMORY_WARNING_THRESHOLD", "70")
)

PROCESS_MEMORY_CRITICAL_THRESHOLD = float(
    os.getenv("PROCESS_MEMORY_CRITICAL_THRESHOLD", "85")
)